# Generated by Django 5.0.6 on 2024-05-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productmodel_if_published_productmodel_is_draft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='if_published',
            new_name='is_published',
        ),
    ]
