# Generated by Django 5.0.6 on 2024-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productmodel_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='attributes',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_variations',
            field=models.JSONField(default=[]),
        ),
    ]
