# Generated by Django 5.0.6 on 2024-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productmodel_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_variations',
            field=models.JSONField(default=list),
        ),
    ]
