# Generated by Django 5.0.6 on 2024-06-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_productmodel_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_location', models.CharField(default='unknown', max_length=255)),
                ('inventory_stock', models.IntegerField()),
                ('inventory_reservations', models.JSONField(default=list)),
                ('inventory_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productmodel')),
                ('inventory_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
